#!/usr/bin/env gnuplot

set terminal png size 4800, 800
set output 'wave.png'

set xr [22000:34000]

plot 'wave.csv' using 0:($1*0.008 - 70) with lines, \
	 'wave2.csv' using 0:($3*0.01 - 12) with lines

# plot 'wave.csv' using 0:($1*0.008 - 70) with lines, \
# 	 'wave2.csv' using 0:($3*0.01 - 12) with lines, \
#      'wave2.csv' using 0:($4) with lines, \
#      'wave2.csv' using 0:($5) with lines, \
#      'wave2.csv' using 0:(-12):6 with labels
